# Generated by Django 4.0.5 on 2022-06-04 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import notes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название заметки')),
                ('note', models.TextField(default='', verbose_name='Описание')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публично')),
                ('importance', models.BooleanField(default=False, verbose_name='Важность')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('up_to', models.DateTimeField(default=notes.models.for_date_plus_one, verbose_name='Выполнить до')),
                ('status', models.IntegerField(choices=[(0, 'Отложена'), (1, 'Активна'), (2, 'Выполнена')], default=1, verbose_name='Статус выполнения')),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
